# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 20:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musical_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Instrumento Musical',
                'verbose_name_plural': 'Instrumentos Musicales',
            },
        ),
        migrations.CreateModel(
            name='UserMusicalInstrumentStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musical_instruments', models.ManyToManyField(related_name='user_musical_instrument', to='musical_group.MusicalStyle')),
                ('musical_styles', models.ManyToManyField(to='musical_group.MusicalStyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Musico Intrumento y Estilo',
                'verbose_name_plural': 'Musicos Instrumento y Estilos',
            },
        ),
        migrations.AlterField(
            model_name='musicalgroup',
            name='directors',
            field=models.ManyToManyField(to='musical_group.UserMusicalInstrumentStyle'),
        ),
        migrations.AlterField(
            model_name='musicalgroup',
            name='guest_musician',
            field=models.ManyToManyField(blank=True, related_name='guest_musicians', to='musical_group.UserMusicalInstrumentStyle'),
        ),
        migrations.AlterField(
            model_name='musicalgroup',
            name='permanent_musician',
            field=models.ManyToManyField(blank=True, related_name='permanent_musicians', to='musical_group.UserMusicalInstrumentStyle'),
        ),
        migrations.AlterField(
            model_name='song',
            name='guest_musician',
            field=models.ManyToManyField(blank=True, related_name='song_guest_musicians', to='musical_group.UserMusicalInstrumentStyle'),
        ),
        migrations.AlterField(
            model_name='song',
            name='permanent_musician',
            field=models.ManyToManyField(blank=True, related_name='song_permanent_musicians', to='musical_group.UserMusicalInstrumentStyle'),
        ),
    ]
