# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='musicalgroup',
            name='musical_styles',
            field=models.ManyToManyField(to='musical_group.MusicalStyle'),
        ),
    ]
