# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_group', '0002_auto_20171107_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermusicalinstrumentstyle',
            name='musical_instruments',
            field=models.ManyToManyField(related_name='user_musical_instrument', to='musical_group.MusicalInstrument'),
        ),
    ]
