# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musical_group', '0002_auto_20171106_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.AlterModelOptions(
            name='musicalgroup',
            options={'verbose_name': 'Grupo Musical', 'verbose_name_plural': 'Grupos Musicales'},
        ),
        migrations.AlterModelOptions(
            name='musicalstyle',
            options={'verbose_name': 'Estilo Musical', 'verbose_name_plural': 'Estilos Musicales'},
        ),
        migrations.AddField(
            model_name='song',
            name='musical_styles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musical_group.MusicalGroup'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='musical_group.Song'),
        ),
    ]
