# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('musical_group', '0003_auto_20171107_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='creation_date',
            field=models.DateField(default='1988-05-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(minutes=1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermusicalinstrumentstyle',
            name='musical_instruments',
            field=models.ManyToManyField(related_name='musical_instrument', to='musical_group.MusicalInstrument'),
        ),
    ]
