# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musical_group', '0003_auto_20171106_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='musical_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musical_group.MusicalGroup'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='song',
            name='musical_styles',
        ),
        migrations.AddField(
            model_name='song',
            name='musical_styles',
            field=models.ManyToManyField(to='musical_group.MusicalStyle'),
        ),
    ]
