# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musical_group', '0004_auto_20171106_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalgroup',
            name='directors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
