# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_group', '0004_auto_20171108_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='upload',
            field=models.FileField(default=1, upload_to='songs/'),
            preserve_default=False,
        ),
    ]
