# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 14:19
from __future__ import unicode_literals

import apps.musical_group.models
import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_group', '0005_song_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='upload',
            field=models.FileField(upload_to=apps.musical_group.models.directory_path),
        ),
    ]
