# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 14:25
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_group', '0006_auto_20171109_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalgroup',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
