# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 04:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musical_group', '0006_auto_20171107_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='guest_musician',
            field=models.ManyToManyField(blank=True, related_name='song_guest_musicians', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='permanent_musician',
            field=models.ManyToManyField(blank=True, related_name='song_permanent_musicians', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musicalgroup',
            name='guest_musician',
            field=models.ManyToManyField(blank=True, related_name='guest_musicians', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musicalgroup',
            name='permanent_musician',
            field=models.ManyToManyField(blank=True, related_name='permanent_musicians', to=settings.AUTH_USER_MODEL),
        ),
    ]
