# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_group', '0007_auto_20171107_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalgroup',
            name='color',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='color',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='color',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
