# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_ed',
            new_name='end_dt',
        ),
    ]
