# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20171110_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_dt',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_dt',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
